### ISSUE TITLE
Expand dat support

### ISSUE THREAD

**Issue by aboutaaron** [palewire/django-calaccess-raw-data#1185]
This is a general ticket for integrating our data pipeline into [maxogden/dat](https://github.com/maxogden/dat).

See #282 and #281 for other dat related tickets.

**Comment by palewire** [comment]
Not a bad a idea to roll up all of our DAT tickets. I would also add #1147 and #1146 since the dat team has told us that unique keys are necessary to using their product.

**Comment by palewire** [comment]
Also #280

**Comment by palewire** [comment]
To simplify things, lets consolidate all of the dat tickets into this one with a more straightforward checklist of work to be done.

- [ ] Determine how many models are missing unique keys
- [ ] Define unique keys defined for all data tables
- [ ] Develop a management command that verifies unique keys against the raw data (#1146)
- [ ] Develop a management command to guess any missing unique keys by querying the database (#1147)
- [ ] Upgrade our pydat wrapper and aim for Python 3 support (#282)
- [ ] Integrate dat into unittests (#281)
- [ ] Add dat usage and development guides to the documentation (#280)

**Comment by emilbayes** [comment]
So I gave @aboutaaron a few pointers on this at NICAR16, and you might want to watch what @karissa is doing with the (publicbits/publicbits.org)[https://github.com/publicbits/publicbits.org] project. `dat` requires a local installation of Node.js and the dat cli. I don't know if publicbits.org will allow you to send your data straight there and get around having Node.js as a dependency of the project

**Comment by aboutaaron** [comment]
Dat has us featured on their site though data is a month old: https://datproject.org/view/79cf7ecc9baf627642099542b3714bbef51810da9f541eabb761029969d0161b

We should reach out to Karissa, Max and co. and ensure that they're pulling our latest data. I'll email 'em shortly.
